CREATE TABLE nome_tabela AS (SELECT "seq","matricula","nome","AnoLetivoIntegralizacao","AnoLetivoPrevisãoConclusao","AnoConclusao","AnoConclusaoEnsinoAnterior",
							"AnoIngresso","bairro","cpf","campus","ChaveResponsavel","cidade","convenio","CotaMEC","CotaSistec",
							"codigo_curso","CodigoEducacenso","DadosProcessoSeletivo","DataColacaoGrau","DataDefesaTCC","DataConclusaoCurso",
							"DataConclusaoIntercambio","DataIntegralizacao","DataMatricula","DataNascimento","DataUltimoProcedimento",
							"deficiencia","DescricaoCurso","diretoria","EditalIngresso","EmailAcademico","EmailGoogleClassroom","EmailResponsavel",
							"endereco","estado","EstadoCivil","Etnia","FormaIngresso","FrequenciaPeriodo","I.R.A.","matriz","modalidade",
							"MunicipioResidencia","MunicipioResidencia-CodigoIBGE","nacionalidade","naturalidade","Naturalidade-CodigoIBGE",
							"NaturezaParticipacao","NomeMae","NomePai","N_Pasta","NivelEnsino","ObservacaoHistorico","observacoes",
							"PastaDocumental","PaisOrigem","PercentualProgresso","PeriodoAtual","PeriodoLetivoIntegralizacao","PeriodoIngresso","polo",
							"rg","RegistroEmissaoDiploma","RendaPerCapita","responsavel","sexo","SituacaoCurso","Situacao Periodo","superdotacao",
							"telefone","TipoEscolaOrigem","TipoDiploma","TransporteEscolar-PoderPublico","Transport Escolar-TipoVeiculo","transtorno",
							"turma","turno","ZonaResidencial","PraticaProfissional Pendente","ColacaoGrauPendente","AtividadesComplementaresPendente",
							"CargaHorariaTCCPendente","CargaHorariaPraticaProfissionalPendente","RegistroTCCPendente","CargaHorariaSeminarioPendente",
							"CargaHorariaEletivaPendente","CargaHorariaOptativaPendente","CargaHorariaObrigatoriaPendente",
							"RegistroENADE","matriculado","cancelado","jubilado","primaria","anocorrente" FROM infogeral1)