CREATE TABLE curso_grad_dim AS (SELECT 
								"codigo_curso",
								"seq",
								"CodigoEducacenso",
								"DescricaoCurso",
								"diretoria",
								"EditalIngresso",
								"matriz",
								"modalidade",
								"NivelEnsino",
								"polo",
								"TipoDiploma",
								"turno",
								"RegistroENADE",
								"primaria",
								"anocorrente",
								"chave_curso",
								"vagas",
								"periodo_integralizacao" FROM curso_dim)