CREATE TABLE aluno_dim AS (SELECT "seq","AnoLetivoPrevisãoConclusao","AnoConclusao","AnoConclusaoEnsinoAnterior",
							"AnoIngresso","cidade",
							"DadosProcessoSeletivo","DataColacaoGrau","DataDefesaTCC","DataConclusaoCurso",
							"DataMatricula","DataNascimento","DataUltimoProcedimento",
							"deficiencia","EditalIngresso",
							"estado","EstadoCivil","Etnia","FormaIngresso","FrequenciaPeriodo","I.R.A.",
							"MunicipioResidencia","MunicipioResidencia-CodigoIBGE","nacionalidade","naturalidade","Naturalidade-CodigoIBGE",
							"NaturezaParticipacao","N_Pasta","NivelEnsino","ObservacaoHistorico","observacoes",
							"PaisOrigem","PercentualProgresso","PeriodoAtual","PeriodoIngresso",
							"RendaPerCapita","sexo","SituacaoCurso","Situacao Periodo",
							"TipoEscolaOrigem","TipoDiploma","TransporteEscolar-PoderPublico","Transport Escolar-TipoVeiculo","transtorno",
							"turma","ZonaResidencial","PraticaProfissional Pendente","ColacaoGrauPendente","AtividadesComplementaresPendente",
							"CargaHorariaTCCPendente","CargaHorariaPraticaProfissionalPendente","RegistroTCCPendente","CargaHorariaSeminarioPendente",
							"CargaHorariaEletivaPendente","CargaHorariaOptativaPendente","CargaHorariaObrigatoriaPendente",
							"RegistroENADE","matriculado","cancelado","jubilado","primaria" FROM infogeral1)